import { useId } from 'react'

/**
 * Brand mark (TR-07): two stacked supplier "document cards" on the blue
 * brand gradient. This is an exact SVG reproduction of the desktop icon
 * generated by backend/cmd/genicons (same palette, geometry and 22% corner
 * radius), so the in-app logo, favicon and installed icon read as one mark.
 * viewBox is a 100×100 grid mirroring the Go rasterizer's percentages.
 */
export function Logo({ size = 32, className }: { size?: number; className?: string }) {
  // Unique per instance: the header and boot screen never coexist, but the
  // gradient id must not collide when the mark is rendered more than once.
  const gid = `logo-grad-${useId()}`
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      role="img"
      aria-label="Supplider"
      className={className}
    >
      <defs>
        <linearGradient id={gid} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#2563eb" />
          <stop offset="1" stopColor="#1e40af" />
        </linearGradient>
      </defs>
      {/* Rounded-square background, brand 500 → 700 vertical gradient. */}
      <rect x="0" y="0" width="100" height="100" rx="22" ry="22" fill={`url(#${gid})`} />
      {/* Back card: peeks out top-right, translucent white. */}
      <rect x="35" y="16" width="46" height="54" rx="7" ry="7" fill="#ffffff" opacity="0.43" />
      {/* Front card: solid white, centered low-left. */}
      <rect x="24" y="27" width="46" height="54" rx="7" ry="7" fill="#ffffff" />
      {/* Three brand-600 "text lines" on the front card. */}
      <rect x="32" y="42.1" width="26" height="4.5" rx="2.25" ry="2.25" fill="#1d4ed8" />
      <rect x="32" y="52.9" width="21" height="4.5" rx="2.25" ry="2.25" fill="#1d4ed8" />
      <rect x="32" y="63.7" width="15" height="4.5" rx="2.25" ry="2.25" fill="#1d4ed8" />
    </svg>
  )
}
