// One-off codegen for the region cascader data (TR-04). The source dataset is
// the MIT-licensed `element-china-area-data` npm package, which is NOT kept as
// a runtime dependency (the personal build stays zero-dep and the bundle only
// ships the compact three-level table below).
//
// Regenerate when administrative divisions change:
//   npm i --no-save --registry=https://registry.npmmirror.com element-china-area-data
//   node scripts/gen-regions.mjs
//
// Output conventions match backend domain.Region short names: province/city
// WITHOUT suffix (浙江/杭州), district WITH suffix (西湖区/义乌市/龙游县).
import { writeFileSync } from 'node:fs'
import { regionData } from 'element-china-area-data'

const shortProvince = (label) =>
  label.replace(/(壮族|回族|维吾尔族)?自治区$/, '').replace(/特别行政区$/, '').replace(/[省市]$/, '')

// The 56 recognised ethnic groups (plus their shortened forms) that appear
// in autonomous-prefecture names. An explicit list avoids the greedy-prefix
// bug (恩施土家族苗族自治州 must be 恩施, not 恩).
const ETHNIC_TOKENS = [
  '维吾尔', '哈萨克', '柯尔克孜', '塔吉克', '乌孜别克', '俄罗斯', '鄂温克', '鄂伦春',
  '达斡尔', '莫力达瓦', '蒙古', '土家族', '苗族', '彝族', '藏族', '布依族', '侗族',
  '瑶族', '白族', '哈尼族', '傣族', '黎族', '傈僳族', '佤族', '畲族', '拉祜族', '水族',
  '纳西族', '景颇族', '羌族', '仫佬族', '毛南族', '撒拉族', '仡佬族', '锡伯族',
  '阿昌族', '普米族', '怒族', '德昂族', '裕固族', '保安族', '京族', '独龙族',
  '赫哲族', '门巴族', '珞巴族', '基诺族', '高山族', '布朗族', '回族', '壮族', '满族',
]

const shortCity = (label) => {
  let s = label.replace(/市$/, '')
  // "省直辖县级行政区划" is the dataset's bucket for county-level cities
  // directly under the province (济源/仙桃/五指山…); keep the full label.
  if (s === '省直辖县级行政区划') return s
  if (/(自治州|自治县|地区|盟)$/.test(s)) {
    s = s.replace(/(自治州|自治县|地区|盟)$/, '')
    const ethnic = new RegExp(`(?:${ETHNIC_TOKENS.join('|')})+$`)
    s = s.replace(ethnic, '')
  }
  return s
}

const MUNICIPALITIES = new Set(['北京市', '天津市', '上海市', '重庆市'])

const provinces = []
const cities = {}
const districts = {}

for (const prov of regionData) {
  const p = shortProvince(prov.label)
  provinces.push(p)
  const cityList = []
  for (const cityNode of prov.children) {
    if (MUNICIPALITIES.has(prov.label)) {
      // 北京 → city "北京"; districts live under 市辖区/县 nodes.
      cityList.push(p)
      districts[`${p}|${p}`] = cityNode.children.map((d) => d.label)
      continue
    }
    const c = shortCity(cityNode.label)
    if (!cityList.includes(c)) cityList.push(c)
    districts[`${p}|${c}`] = cityNode.children.map((d) => d.label)
  }
  cities[p] = cityList
}

const banner =
  '// AUTO-GENERATED by scripts/gen-regions.mjs — do not edit by hand.\n' +
  '// Source: element-china-area-data (MIT). Short-name provinces/cities;\n' +
  '// district labels keep their 区/县/市 suffix.\n\n'

const body =
  banner +
  `export const REGION_PROVINCES: string[] = ${JSON.stringify(provinces)}\n\n` +
  `export const REGION_CITIES: Record<string, string[]> = ${JSON.stringify(cities)}\n\n` +
  `export const REGION_DISTRICTS: Record<string, string[]> = ${JSON.stringify(districts)}\n`

writeFileSync(new URL('../src/regions.data.ts', import.meta.url), body)
console.log(
  `provinces=${provinces.length} cityRows=${Object.keys(cities).length} districtRows=${Object.keys(districts).length}`,
)
